### ISSUE TITLE
messages from kafka topic not inserted in scylla db

### ISSUE THREAD

**Issue by HARIHARAN1103** [scylladb/kafka-connect-scylladb#32]
after loading the connector using  Kafka-connect-scylladb.json,  no messages are inserted in Scylla DB.

**Comment by HARIHARAN1103** [comment]
Followed the quickstart
https://github.com/scylladb/kafka-connect-scylladb/blob/master/documentation/QUICKSTART.md

but scylla db is not started using docker image, since  Scylla DB is already present in the  machine with below version:

**ScyllaDB: cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4**

checked plugin loader using:

` curl -sS localhost:8083/connector-plugins | jq .[].class | grep ScyllaDbSinkConnector`

and got the ouput as mentioned in quick start:

**"io.connect.scylladb.ScyllaDbSinkConnector"**
below **Kafka-connect-scylladb.json** load connector config is used 
```
{
     "name" : "scylladb-sink-connector",
     "config" : {
       "connector.class" : "io.connect.scylladb.ScyllaDbSinkConnector",
       "tasks.max" : "1",
       "topics" : "topic1,topic2,mqtt-malaria",
       "scylladb.contact.points" : "localhost:9042",
       "scylladb.keyspace" : "mqtest"
       }
}
```

tried the same message to check:

```
kafka-avro-console-producer 
--broker-list localhost:9092 
--topic topic1  
--property parse.key=true 
--property key.schema='{"type":"record","name":"key_schema","fields":[{"name":"id","type":"int"}]}' 
--property "key.separator=$" 
--property value.schema='{"type":"record","name":"value_schema","fields":[{"name":"id","type":"int"},
{"name":"firstName","type":"string"},{"name":"lastName","type":"string"}]}'

```

even after creating a table with keyspace maually, the messages are not inserted in DB.

Is that any config or setup is missed in the quick start? any config is need to add in Kafka? How to confirm Scylla is connected to kafka

**Comment by avelanarius** [comment]
Could you also post messages on the topic? 
Command to do it:
```
kafka-avro-console-consumer --broker-list localhost:9092 --topic topic1 --from-beginning --property print.key=true
``` 
(note that on my system `--broker-list` is called `--bootstrap-server`)

And also print logs of connector?
Command to do it:
```
confluent local services connect log
```
(command as of Confluent 6.0.0, if it doesn't work maybe look at `/tmp/confluent.XXXXXX/connect/logs/connect.log`, where `XXXXXX` are some numbers)

**Comment by HARIHARAN1103** [comment]
> Could you also post messages on the topic?
> Command to do it:
> 
> ```
> kafka-avro-console-consumer --broker-list localhost:9092 --topic topic1 --from-beginning --property print.key=true
> ```
> 
> (note that on my system `--broker-list` is called `--bootstrap-server`)
> 
> And also print logs of connector?
> Command to do it:
> 
> ```
> confluent local services connect log
> ```
> 
> (command as of Confluent 6.0.0, if it doesn't work maybe look at `/tmp/confluent.XXXXXX/connect/logs/connect.log`, where `XXXXXX` are some numbers)

posted messages are hitting in consumer, Scylla DB  connection issue exists.

```
{
     "name" : "scylladb-sink-connector",
     "config" : {
       "connector.class" : "io.connect.scylladb.ScyllaDbSinkConnector",
       "tasks.max" : "1",
       "topics" : "topic1,topic2,mqtt-malaria",
       "scylladb.contact.points" : "localhost:9042",
       "scylladb.keyspace" : "mqtest"
       }
}
```

what value does the  **scylladb.contact.points**  refers ? 

checked **confluent local services connect log**

```
 (io.connect.scylladb.ScyllaDbSinkConnectorConfig:361)
[2021-03-18 04:41:57,520] INFO Trying to configure address translator for private network address and port. (io.connect.scylladb.ScyllaDbSessionFactory:152)
[2021-03-18 04:41:57,522] INFO Failed to configure address translator, provide a valid JSON string with external network address and port mapped to private network address and port. (io.connect.scylladb.ScyllaDbSessionFactory:54)
[2021-03-18 04:41:57,522] INFO Configuring public contact points=localhost:9042 (io.connect.scylladb.ScyllaDbSessionFactory:145)
[2021-03-18 04:41:57,546] ERROR WorkerConnector{id=scylladb-sink-connector} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector:194)
java.lang.IllegalArgumentException: Failed to add contact point: localhost:9042
	at com.datastax.driver.core.Cluster$Builder.addContactPoint(Cluster.java:925)
	at com.datastax.driver.core.Cluster$Builder.addContactPoints(Cluster.java:945)
	at io.connect.scylladb.ScyllaDbSessionFactory.configurePublicContactPoints(ScyllaDbSessionFactory.java:148)
	at io.connect.scylladb.ScyllaDbSessionFactory.newSession(ScyllaDbSessionFactory.java:57)
	at io.connect.scylladb.ScyllaDbSinkConnector.start(ScyllaDbSinkConnector.java:48)
	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:186)
	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:211)
	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:350)
	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:333)
	at org.apache.kafka.connect.runtime.WorkerConnector.doRun(WorkerConnector.java:141)
	at org.apache.kafka.connect.runtime.WorkerConnector.run(WorkerConnector.java:118)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: localhost:9042: Temporary failure in name resolution
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at com.datastax.driver.core.Cluster$Builder.addContactPoint(Cluster.java:922)
	... 15 more
[2021-03-18 04:41:57,551] ERROR [Worker clientId=connect-1, groupId=connect-cluster] Failed to start connector 'scylladb-sink-connector' (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1339)
org.apache.kafka.connect.errors.ConnectException: Failed to start connector: scylladb-sink-connector
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$startConnector$5(DistributedHerder.java:1305)
	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:336)
	at org.apache.kafka.connect.runtime.WorkerConnector.doRun(WorkerConnector.java:141)
	at org.apache.kafka.connect.runtime.WorkerConnector.run(WorkerConnector.java:118)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by avelanarius** [comment]
> and passed message in topic1 as :
> `{"schema":{"type":"struct","fields":[{"type":"int32","optional":false,"field":"id"},{"type":"string","optional":false,"field":"emailid"},{"type":"string","optional":false,"field":"ip"},{"type":"string","optional":false,"field":"browser"},{"type":"string","optional":false,"field":"pagetype"}],"payload":{"id":1,"emailid":"uaer@gmail.com","ip":"172.123.145.000","browser":"chrome6.0","pagetype":"home"}}}`
> 
> message in consumer:
> 
> ```
> ./bin/kafka-console-consumer --topic topic1 --from-beginning --bootstrap-server localhost:9092 --property print.key=true
> 
> null	{"schema":{"type":"map","fields":[{"type":"int32","optional":false,"field":"id"},{"type":"string","optional":false,"field":"emailid"},{"type":"string","optional":false,"field":"ip"},{"type":"string","optional":false,"field":"browser"},{"type":"string","optional":false,"field":"pagetype"}],"payload":{"id":1,"emailid":"uaer@gmail.com","ip":"172.123.145.000","browser":"chrome6.0","pagetype":"home"}}}
> ```

So the problem is that your messages in Kafka don't have a key properly set (the key is `null`, as printed by `kafka-console-consumer`). The key should be filled in and only contain fields that will be a part of PRIMARY KEY in destination Scylla cluster.

I see that you tried to use `ValueToKey`, but it fails (this is not a part of Scylla Sink Connector). My guess is that you are using `org.apache.kafka.connect.storage.StringConverter` instead of `org.apache.kafka.connect.json.JsonConverter` and because of that `ValueToKey` can't extract `id` field.

**Comment by avelanarius** [comment]
I have been successfully able to configure the connector with the following configuration:
```
{
  "name": "scylladb-sink-connector",
  "config": {
    "connector.class": "io.connect.scylladb.ScyllaDbSinkConnector",
    "tasks.max": "1",
    "key.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "transforms": "createKey",
    "topics": "topic1",
    "transforms.createKey.type": "org.apache.kafka.connect.transforms.ValueToKey",
    "transforms.createKey.fields": "id",
    "scylladb.contact.points": "127.0.0.1",
    "scylladb.port": "9042",
    "scylladb.keyspace": "ks",
    "key.converter.schemas.enable": "true",
    "value.converter.schemas.enable": "true"
  }
}
```

And by sending the following message to a topic. 
```
{"schema":{"type":"struct","fields":[{"type":"int32","optional":false,"field":"id"},{"type":"string","optional":false,"field":"emailid"},{"type":"string","optional":false,"field":"ip"},{"type":"string","optional":false,"field":"browser"},{"type":"string","optional":false,"field":"pagetype"}]},"payload":{"id":1,"emailid":"uaer@gmail.com","ip":"172.123.145.000","browser":"chrome6.0","pagetype":"home"}}
```

Before, your posted JSON was invalid, as the `payload` field was erroneously in `schema` instead of being top level:
![Invalid and valid JSON](https://user-images.githubusercontent.com/10003183/111617094-fc4a0480-87e2-11eb-8576-97a3b2cfe692.png)

**Comment by HARIHARAN1103** [comment]
> I have been successfully able to configure the connector with the following configuration:
> 
> ```
> {
>   "name": "scylladb-sink-connector",
>   "config": {
>     "connector.class": "io.connect.scylladb.ScyllaDbSinkConnector",
>     "tasks.max": "1",
>     "key.converter": "org.apache.kafka.connect.json.JsonConverter",
>     "value.converter": "org.apache.kafka.connect.json.JsonConverter",
>     "transforms": "createKey",
>     "topics": "topic1",
>     "transforms.createKey.type": "org.apache.kafka.connect.transforms.ValueToKey",
>     "transforms.createKey.fields": "id",
>     "scylladb.contact.points": "127.0.0.1",
>     "scylladb.port": "9042",
>     "scylladb.keyspace": "ks",
>     "key.converter.schemas.enable": "true",
>     "value.converter.schemas.enable": "true"
>   }
> }
> ```
> 
> And by sending the following message to a topic.
> 
> ```
> {"schema":{"type":"struct","fields":[{"type":"int32","optional":false,"field":"id"},{"type":"string","optional":false,"field":"emailid"},{"type":"string","optional":false,"field":"ip"},{"type":"string","optional":false,"field":"browser"},{"type":"string","optional":false,"field":"pagetype"}]},"payload":{"id":1,"emailid":"uaer@gmail.com","ip":"172.123.145.000","browser":"chrome6.0","pagetype":"home"}}
> ```
> 
> Before, your posted JSON was invalid, as the `payload` field was erroneously in `schema` instead of being top level:
> ![Invalid and valid JSON](https://user-images.githubusercontent.com/10003183/111617094-fc4a0480-87e2-11eb-8576-97a3b2cfe692.png)

It was a documentation issue, noticed that one, now the messages are inserting. Thanks for reply!

**Comment by HARIHARAN1103** [comment]
> Could you also post messages on the topic?
> Command to do it:
> 
> ```
> kafka-avro-console-consumer --broker-list localhost:9092 --topic topic1 --from-beginning --property print.key=true
> ```
> 
> (note that on my system `--broker-list` is called `--bootstrap-server`)
> 
> And also print logs of connector?
> Command to do it:
> 
> ```
> confluent local services connect log
> ```
> 
> (command as of Confluent 6.0.0, if it doesn't work maybe look at `/tmp/confluent.XXXXXX/connect/logs/connect.log`, where `XXXXXX` are some numbers)

Have you tried avro format, I was able to connect and insert the messages only on above tried json-schema-payload method , Is config varies for avro format.

In my case, the message is being published from snowplow-thrift , so from consumer message i need to create a similar avro-producer and to dumb in scylla db.

Here is my conumer message sample :

`{"ip":{"string":"37.47.61.165"},"browser":{"string":"Mozilla/5.0 (Linux; Android 6.0.1; SM-A500FU) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Mobile Safari/537.36"}}
`
