### ISSUE TITLE
Connector failed to start with java.lang.NoClassDefFoundError: com/datastax/driver/core/Statement

### ISSUE THREAD

**Issue by mango009** [scylladb/kafka-connect-scylladb#83]
First problem:

The documentation on the Scylla website and the [quick start in the repo](https://github.com/scylladb/kafka-connect-scylladb/blob/master/documentation/QUICKSTART.md) seems wrong to me. It stated:

```
After completion of the above steps, a folder by the name of ‘components’ will be created in the target folder of the source code folder. The Connector jar files are present in {source-code-folder}/target/components/packages/[jar-files]
```

But after doing `mvn install -DskipTests` the the packages directory actually looks like:

```
target/components/packages/
├── ScyllaDB-kafka-connect-scylladb-1.0.1-preview
│   └── ScyllaDB-kafka-connect-scylladb-1.0.1-preview
│       ├── doc
│       │   ├── LICENSE
│       │   └── README.md
│       ├── etc
│       │   ├── connect-avro-standalone-local.properties
│       │   ├── connect-log4j.properties
│       │   └── scylladb-sink-quickstart.properties
│       ├── lib
│       │   ├── animal-sniffer-annotations-1.14.jar
│       │   ├── asm-5.0.3.jar
│       │   ├── asm-analysis-5.0.3.jar
│       │   ├── asm-commons-5.0.3.jar
│       │   ├── asm-tree-5.0.3.jar
......
```

And `kafka-connect-scylladb-1.0.1.jar` it is generated right under `target/components/`.

Second problem:

I created a directory and copy all the jars under `target/components/packages/ScyllaDB-kafka-connect-scylladb-1.0.1-preview/ScyllaDB-kafka-connect-scylladb-1.0.1-preview/lib` and `kafka-connect-scylladb-1.0.1.jar` to the directory.

I then started the connector but getting an exception (sorry the stack trace is long):

```
[2022-11-27 14:17:45,142] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/netty-transport-4.1.77.Final.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,171] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/netty-transport-4.1.77.Final.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,171] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/jffi-1.2.16-native.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,172] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/jffi-1.2.16-native.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,172] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/jsr305-1.3.9.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,175] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/jsr305-1.3.9.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,176] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/jffi-1.2.16.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,184] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/jffi-1.2.16.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,184] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/netty-common-4.1.77.Final.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,207] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/netty-common-4.1.77.Final.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,207] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/jnr-x86asm-1.0.2.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,215] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/jnr-x86asm-1.0.2.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,215] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/netty-tcnative-2.0.7.Final.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,217] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/netty-tcnative-2.0.7.Final.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,217] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/slf4j-api-1.7.25.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,221] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/slf4j-api-1.7.25.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,221] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/error_prone_annotations-2.1.3.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,223] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/error_prone_annotations-2.1.3.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,223] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/jackson-core-2.13.4.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,236] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/jackson-core-2.13.4.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,236] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/asm-commons-5.0.3.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,240] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/asm-commons-5.0.3.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,240] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/jnr-constants-0.9.9.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,248] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/jnr-constants-0.9.9.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,249] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/netty-codec-4.1.77.Final.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,259] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/netty-codec-4.1.77.Final.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,259] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/jackson-annotations-2.13.4.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,264] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/jackson-annotations-2.13.4.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,264] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/scylla-driver-extras-3.11.0.1.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,269] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/scylla-driver-extras-3.11.0.1.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,269] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/netty-buffer-4.1.77.Final.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,277] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/netty-buffer-4.1.77.Final.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,278] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/connect-utils-0.1.18.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,280] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/connect-utils-0.1.18.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,280] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/checker-compat-qual-2.0.0.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,282] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/checker-compat-qual-2.0.0.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,282] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/asm-util-5.0.3.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,286] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/asm-util-5.0.3.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,286] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/j2objc-annotations-1.1.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,287] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/j2objc-annotations-1.1.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,287] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/jackson-databind-2.13.4.2.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,333] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/jackson-databind-2.13.4.2.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,333] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/metrics-core-3.2.2.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,338] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/metrics-core-3.2.2.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,338] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/asm-5.0.3.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,341] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/asm-5.0.3.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,342] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/asm-analysis-5.0.3.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,344] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/asm-analysis-5.0.3.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,344] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/guava-24.1.1-jre.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,409] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/guava-24.1.1-jre.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,409] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/netty-resolver-4.1.77.Final.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,411] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/netty-resolver-4.1.77.Final.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,411] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/freemarker-2.3.25-incubating.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,447] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/freemarker-2.3.25-incubating.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,447] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/animal-sniffer-annotations-1.14.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,448] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/animal-sniffer-annotations-1.14.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,448] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/netty-handler-4.1.77.Final.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,462] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/netty-handler-4.1.77.Final.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,463] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/jnr-ffi-2.1.7.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,479] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/jnr-ffi-2.1.7.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,479] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/json-20160810.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,482] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/json-20160810.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,482] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/scylla-driver-core-3.11.2.0.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,513] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/scylla-driver-core-3.11.2.0.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,514] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/netty-transport-native-epoll-4.1.77.Final.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,515] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/netty-transport-native-epoll-4.1.77.Final.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,515] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/netty-transport-native-unix-common-4.1.77.Final.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,517] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/netty-transport-native-unix-common-4.1.77.Final.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,518] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/jnr-posix-3.0.44.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,526] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/jnr-posix-3.0.44.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,526] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/netty-transport-classes-epoll-4.1.77.Final.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,534] INFO Registered loader: PluginClassLoader{pluginLocation=file:/Users/mango/tools/confluent-7.3.0/share/scylla-connectors/netty-transport-classes-epoll-4.1.77.Final.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:299)
[2022-11-27 14:17:45,534] INFO Loading plugin from: /Users/mango/tools/confluent-7.3.0/share/scylla-connectors/kafka-connect-scylladb-1.0.1.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:277)
[2022-11-27 14:17:45,537] ERROR Stopping due to error (org.apache.kafka.connect.cli.ConnectStandalone:126)
java.lang.NoClassDefFoundError: com/datastax/driver/core/Statement
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
	at java.base/java.lang.Class.getConstructor0(Class.java:3578)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.versionFor(DelegatingClassLoader.java:441)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.getPluginDesc(DelegatingClassLoader.java:405)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanPluginPath(DelegatingClassLoader.java:366)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanUrlsAndAddPlugins(DelegatingClassLoader.java:298)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.registerPlugin(DelegatingClassLoader.java:291)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initPluginLoader(DelegatingClassLoader.java:260)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initLoaders(DelegatingClassLoader.java:238)
	at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:60)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:78)
Caused by: java.lang.ClassNotFoundException: com.datastax.driver.core.Statement
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:103)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 13 more
```

**Comment by Bouncheck** [comment]
Hi, this seems to be a misconfiguration issue. In your case copying over topmost `ScyllaDB-kafka-connect-scylladb-1.0.1-preview` folder, the one inside `packages` directory should suffice.

I can see that quickstart document seems a little unclear about this part, so I've modified it a little in a recent pull request. Hopefully that helps.

What I think happened in your case is that files you copied over did not get recognized as parts of a single plugin and therefore ended up isolated from each other and that's why connector cannot see Statement that's inside another .jar file.
The package under components directory will contain all necessary dependencies and `kafka-connect-scylladb-<version>.jar` will also be present in `lib` subdirectory.
